interface Env { DB: D1Database; ADMIN_USERNAME: string; ADMIN_PASSWORD: string; ALLOWED_ORIGIN?: string; }
type User = { id:string; username:string };
const origin=(request:Request,env:Env)=>{const requestOrigin=request.headers.get('Origin');return env.ALLOWED_ORIGIN ? (requestOrigin===env.ALLOWED_ORIGIN ? env.ALLOWED_ORIGIN : 'null') : (requestOrigin ? 'null' : '*')};
const json=(body:unknown,status=200,request?:Request,env?:Env)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','access-control-allow-origin':request&&env?origin(request,env):'*','access-control-allow-credentials':'true','vary':'Origin'}});
const now=()=>new Date().toISOString();
async function digest(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function passwordHash(password:string,salt:string=crypto.randomUUID()){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return `${salt}:${[...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,'0')).join('')}`}
async function checkPassword(password:string,stored:string){const [salt]=stored.split(':');return stored===await passwordHash(password,salt)}
function cookie(token:string){return `session=${token}; HttpOnly; Secure; SameSite=None; Path=/; Max-Age=604800`}
async function session(request:Request,env:Env):Promise<User|null>{const token=request.headers.get('Cookie')?.match(/session=([^;]+)/)?.[1];if(!token)return null;const hash=await digest(token);return await env.DB.prepare('SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(hash,now()).first<User>()}
function cors(request:Request,env:Env){return {headers:{'Access-Control-Allow-Origin':origin(request,env),'Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Allow-Credentials':'true','Vary':'Origin'}}}
export default {async fetch(request:Request,env:Env){if(request.method==='OPTIONS')return new Response(null,{headers:cors(request,env).headers});const url=new URL(request.url);try{
 if(url.pathname==='/api/auth/register'&&request.method==='POST'){const b=await request.json() as {username?:string,password?:string,invite?:string};if(!b.username||!b.password||!b.invite||b.username.length>24||b.password.length<8)return json({error:'请输入有效用户名、密码（至少 8 位）和邀请码'},400,request,env);const invite=await env.DB.prepare('SELECT code FROM invite_codes WHERE code=? AND used_by IS NULL AND revoked=0').bind(b.invite).first();if(!invite)return json({error:'邀请码无效或已使用'},400,request,env);const exists=await env.DB.prepare('SELECT id FROM users WHERE username=?').bind(b.username).first();if(exists)return json({error:'用户名已存在'},409,request,env);const id=crypto.randomUUID(),hash=await passwordHash(b.password);await env.DB.batch([env.DB.prepare('INSERT INTO users VALUES (?,?,?,?)').bind(id,b.username,hash,now()),env.DB.prepare('UPDATE invite_codes SET used_by=?,used_at=? WHERE code=?').bind(id,now(),b.invite)]);return json({ok:true},201,request,env)}
 if(url.pathname==='/api/auth/login'&&request.method==='POST'){const b=await request.json() as {username?:string,password?:string};const user=await env.DB.prepare('SELECT * FROM users WHERE username=?').bind(b.username??'').first<User & {password_hash:string}>();if(!user||!(await checkPassword(b.password??'',user.password_hash)))return json({error:'用户名或密码错误'},401,request,env);const token=crypto.randomUUID()+crypto.randomUUID(),hash=await digest(token);await env.DB.prepare('INSERT INTO sessions VALUES (?,?,?)').bind(hash,user.id,new Date(Date.now()+604800000).toISOString()).run();return new Response(JSON.stringify({user:{id:user.id,username:user.username}}),{headers:{...cors(request,env).headers,'content-type':'application/json','Set-Cookie':cookie(token)}})}
 if(url.pathname==='/api/auth/me'){const user=await session(request,env);return user?json({user}):json({user:null},401,request,env)}
 if(url.pathname==='/api/auth/logout'){const token=request.headers.get('Cookie')?.match(/session=([^;]+)/)?.[1];if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(token)).run();return new Response(JSON.stringify({ok:true}),{headers:{...cors(request,env).headers,'Set-Cookie':'session=; HttpOnly; Path=/; Max-Age=0'}})}
 if(url.pathname==='/api/challenge/today'){const date=new Date(Date.now()+8*3600000).toISOString().slice(0,10);const seed=[...date].reduce((a,c)=>((a*31+c.charCodeAt(0))>>>0),7);return json({date,version:1,seed},200,request,env)}
 if(url.pathname==='/api/scores'&&request.method==='POST'){const user=await session(request,env);if(!user)return json({error:'请先登录'},401,request,env);const b=await request.json() as {score?:number,moves?:number,highestLevel?:number,challengeDate?:string,challengeVersion?:number};const date=new Date(Date.now()+8*3600000).toISOString().slice(0,10);const score=b.score;const moves=b.moves;if(b.challengeDate!==date||b.challengeVersion!==1||!Number.isInteger(score)||!Number.isInteger(moves)||moves===undefined||score===undefined||moves<1||moves>30||score<0||score>10000000)return json({error:'成绩校验失败'},400,request,env);await env.DB.prepare('INSERT INTO scores(user_id,challenge_date,score,moves,highest_tile,created_at) VALUES (?,?,?,?,?,?) ON CONFLICT(user_id,challenge_date) DO UPDATE SET score=MAX(score,excluded.score),moves=CASE WHEN excluded.score>score THEN excluded.moves ELSE moves END,highest_tile=MAX(highest_tile,excluded.highest_tile)').bind(user.id,date,score,moves,b.highestLevel??0,now()).run();return json({ok:true},200,request,env)}
 if(url.pathname==='/api/leaderboard'){const period=url.searchParams.get('period')||'daily';const today=new Date(Date.now()+8*3600000);const date=today.toISOString().slice(0,10);const start=new Date(today);if(period==='weekly')start.setUTCDate(start.getUTCDate()-6);const condition=period==='all'?'1=1':period==='weekly'?'s.challenge_date>=?':'s.challenge_date=?';const params=period==='all'?[]:[period==='weekly'?start.toISOString().slice(0,10):date];const rows=await env.DB.prepare(`SELECT u.username,MAX(s.score) AS score,MIN(s.moves) AS moves,MAX(s.highest_tile) AS highest_tile,MAX(s.created_at) AS created_at FROM scores s JOIN users u ON u.id=s.user_id WHERE ${condition} GROUP BY s.user_id ORDER BY score DESC LIMIT 50`).bind(...params).all();return json({items:rows.results},200,request,env)}
 if(url.pathname==='/api/save'&&(request.method==='GET'||request.method==='POST')){const user=await session(request,env);if(!user)return json({error:'请先登录'},401,request,env);if(request.method==='GET'){const save=await env.DB.prepare('SELECT payload,updated_at FROM game_saves WHERE user_id=?').bind(user.id).first();return json({save},200,request,env)}const payload=await request.text();if(payload.length>100000)return json({error:'存档过大'},413,request,env);await env.DB.prepare('INSERT INTO game_saves VALUES (?,?,?) ON CONFLICT(user_id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at').bind(user.id,payload,now()).run();return json({ok:true},200,request,env)}
 if(url.pathname.startsWith('/api/admin/invites')){const auth=request.headers.get('Authorization')?.replace('Basic ','');if(!auth)return json({error:'未授权'},401,request,env);const [u,p]=atob(auth).split(':');if(u!==env.ADMIN_USERNAME||p!==env.ADMIN_PASSWORD)return json({error:'未授权'},401,request,env);if(request.method==='GET'){const rows=await env.DB.prepare('SELECT code,used_by,revoked,created_at,used_at FROM invite_codes ORDER BY created_at DESC LIMIT 100').all();return json({items:rows.results},200,request,env)}if(request.method==='DELETE'){const code=url.searchParams.get('code');if(!code)return json({error:'缺少邀请码'},400,request,env);await env.DB.prepare('UPDATE invite_codes SET revoked=1 WHERE code=? AND used_by IS NULL').bind(code).run();return json({ok:true},200,request,env)}if(request.method==='POST'){const code=crypto.randomUUID().slice(0,8).toUpperCase();await env.DB.prepare('INSERT INTO invite_codes(code,created_at) VALUES (?,?)').bind(code,now()).run();return json({code},201,request,env)}}
 return json({error:'Not found'},404,request,env)}catch(error){console.error(error);return json({error:'服务暂时不可用'},500,request,env)}}};
