interface Env { DB: D1Database; ADMIN_USERNAME: string; ADMIN_PASSWORD: string; }
type User = { id:string; username:string };
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-credentials':'true'}});
const now=()=>new Date().toISOString();
async function digest(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function passwordHash(password:string,salt=crypto.randomUUID()){return `${salt}:${await digest(`${salt}:${password}`)}`}
async function checkPassword(password:string,stored:string){const [salt]=stored.split(':');return stored===await passwordHash(password,salt)}
function cookie(token:string){return `session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=604800`}
async function session(request:Request,env:Env):Promise<User|null>{const token=request.headers.get('Cookie')?.match(/session=([^;]+)/)?.[1];if(!token)return null;const hash=await digest(token);return await env.DB.prepare('SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(hash,now()).first<User>()}
function cors(){return {headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS'}}}
export default {async fetch(request:Request,env:Env){if(request.method==='OPTIONS')return new Response(null,{headers:cors().headers});const url=new URL(request.url);try{
 if(url.pathname==='/api/auth/register'&&request.method==='POST'){const b=await request.json() as {username?:string,password?:string,invite?:string};if(!b.username||!b.password||!b.invite||b.username.length>24||b.password.length<8)return json({error:'请输入有效用户名、密码（至少 8 位）和邀请码'},400);const invite=await env.DB.prepare('SELECT code FROM invite_codes WHERE code=? AND used_by IS NULL AND revoked=0').bind(b.invite).first();if(!invite)return json({error:'邀请码无效或已使用'},400);const exists=await env.DB.prepare('SELECT id FROM users WHERE username=?').bind(b.username).first();if(exists)return json({error:'用户名已存在'},409);const id=crypto.randomUUID(),hash=await passwordHash(b.password);await env.DB.batch([env.DB.prepare('INSERT INTO users VALUES (?,?,?,?)').bind(id,b.username,hash,now()),env.DB.prepare('UPDATE invite_codes SET used_by=?,used_at=? WHERE code=?').bind(id,now(),b.invite)]);return json({ok:true},201)}
 if(url.pathname==='/api/auth/login'&&request.method==='POST'){const b=await request.json() as {username?:string,password?:string};const user=await env.DB.prepare('SELECT * FROM users WHERE username=?').bind(b.username??'').first<User & {password_hash:string}>();if(!user||!(await checkPassword(b.password??'',user.password_hash)))return json({error:'用户名或密码错误'},401);const token=crypto.randomUUID()+crypto.randomUUID(),hash=await digest(token);await env.DB.prepare('INSERT INTO sessions VALUES (?,?,?)').bind(hash,user.id,new Date(Date.now()+604800000).toISOString()).run();return new Response(JSON.stringify({user:{id:user.id,username:user.username}}),{headers:{...cors().headers,'content-type':'application/json','Set-Cookie':cookie(token)}})}
 if(url.pathname==='/api/auth/me'){const user=await session(request,env);return user?json({user}):json({user:null},401)}
 if(url.pathname==='/api/auth/logout'){const token=request.headers.get('Cookie')?.match(/session=([^;]+)/)?.[1];if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(token)).run();return new Response(JSON.stringify({ok:true}),{headers:{...cors().headers,'Set-Cookie':'session=; HttpOnly; Path=/; Max-Age=0'}})}
 if(url.pathname==='/api/leaderboard'){const rows=await env.DB.prepare('SELECT u.username,s.score,s.moves,s.highest_tile,s.created_at FROM scores s JOIN users u ON u.id=s.user_id WHERE s.challenge_date=? ORDER BY s.score DESC LIMIT 50').bind(new Date(Date.now()+8*3600000).toISOString().slice(0,10)).all();return json({items:rows.results})}
 if(url.pathname==='/api/save'&&(request.method==='GET'||request.method==='POST')){const user=await session(request,env);if(!user)return json({error:'请先登录'},401);if(request.method==='GET'){const save=await env.DB.prepare('SELECT payload,updated_at FROM game_saves WHERE user_id=?').bind(user.id).first();return json({save})}const payload=await request.text();if(payload.length>100000)return json({error:'存档过大'},413);await env.DB.prepare('INSERT INTO game_saves VALUES (?,?,?) ON CONFLICT(user_id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at').bind(user.id,payload,now()).run();return json({ok:true})}
 if(url.pathname==='/api/admin/invites'&&request.method==='POST'){const auth=request.headers.get('Authorization')?.replace('Basic ','');if(!auth)return json({error:'未授权'},401);const [u,p]=atob(auth).split(':');if(u!==env.ADMIN_USERNAME||p!==env.ADMIN_PASSWORD)return json({error:'未授权'},401);const code=crypto.randomUUID().slice(0,8).toUpperCase();await env.DB.prepare('INSERT INTO invite_codes(code,created_at) VALUES (?,?)').bind(code,now()).run();return json({code},201)}
 return json({error:'Not found'},404)}catch(error){console.error(error);return json({error:'服务暂时不可用'},500)}}};
